const Products = [
    { Imagen: './img/Imagen1.jpg', Nombre: 'Smart TV 43" Philips', Descripcion: 'El Android TV Philips LED Full HD de 43 pulgadas (modelo 43PFD6917) en elegante negro ofrece una experiencia visual cautivadora y funciones inteligentes avanzadas para streaming, aplicaciones y juegos, brindando entretenimiento sin límites.', Precio: '$169.999', SKU: 'KR3ZQQY8', Stock: '25' },
    { Imagen: './img/Imagen2.jpg', Nombre: 'Notebook Asus Vivobook', Descripcion: 'El portátil Asus Vivobook con procesador Ryzen 7 ofrece un rendimiento excepcional con su potente CPU AMD, 16 GB de RAM y un rápido SSD de 512 GB. Este equipo combina potencia y portabilidad para una experiencia informática versátil y eficiente.', Precio: '$569.999', SKU: 'C5KWZ83Z', Stock: '12' },
    { Imagen: './img/Imagen3.jpg', Nombre: 'Samsung Galaxy A03', Descripcion: 'El Samsung Galaxy A03 en azul ofrece un rendimiento excepcional con 4 GB de RAM y 64 GB de almacenamiento. Con su elegante diseño, pantalla vibrante y potente cámara, es la elección perfecta para tus necesidades móviles.', Precio: '$69.999', SKU: 'NGEMUWFB', Stock: '17' },
    { Imagen: './img/Imagen4.jpg', Nombre: 'Monitor Samsung 24"', Descripcion: 'El Monitor Gamer Samsung F24t35 LED de 24 pulgadas en elegante azul y gris oscuro ofrece una experiencia de juego inmersiva con calidad de color superior y rendimiento excepcional.', Precio: '$113.399', SKU: 'VFHXJRKM', Stock: '14' },
    { Imagen: './img/Imagen5.jpg', Nombre: 'Sony PlayStation 5', Descripcion: 'La Sony PlayStation 5 825GB en color blanco y negro es una potente consola de videojuegos que ofrece gráficos impresionantes y una amplia biblioteca de juegos, brindando una experiencia de juego inmersiva.', Precio: '$991.999', SKU: 'S6PUWF93', Stock: '04' },
    { Imagen: './img/Imagen6.jpg', Nombre: 'Notebook HP 15-ef2514', Descripcion: 'La Notebook HP 15-ef2514la en elegante plata combina un potente rendimiento con un AMD Ryzen 7 5700U, 8GB de RAM y 512GB de SSD, respaldado por gráficos AMD Radeon RX Vega 8. Ideal para productividad y entretenimiento.', Precio: '$799.899', SKU: 'GBPC2WVR', Stock: '02' },
    { Imagen: './img/Imagen7.jpg', Nombre: 'Smart TV LED 55" BGH', Descripcion: 'La Smart TV LED 55" BGH B5522US6A Android es una experiencia audiovisual excepcional. Con Android TV, resolución nítida 4K y conectividad inteligente, disfruta de entretenimiento sin límites en una pantalla impresionante.', Precio: '$280.999', SKU: 'VGAXGEWV', Stock: '16' },
    { Imagen: './img/Imagen8.jpg', Nombre: 'Kindle Paperwhite 11', Descripcion: 'El Ebook Reader Kindle Paperwhite 11 Gen es una revolución en lectura digital. Con 6.8 pulgadas de pantalla, 8GB de almacenamiento y resistencia al agua, ofrece una experiencia inigualable en color negro.', Precio: '$119.999', SKU: 'ZS8FSB7Y', Stock: '13' },
    { Imagen: './img/Imagen9.jpg', Nombre: 'Notebook Dell Inspiron', Descripcion: 'La Notebook Dell Inspiron 3525 con AMD Ryzen 7 ofrece un rendimiento excepcional y almacenamiento rápido con su SSD de 512 GB y 16 GB de RAM, ideal para usuarios exigentes.', Precio: '$769.999', SKU: 'KR3ZQQY8', Stock: '11' },
    { Imagen: './img/Imagen10.jpg', Nombre: 'Moto G23 128 GB', Descripcion: 'El Moto G23 en elegante pearl white es un smartphone potente y elegante con 128 GB de almacenamiento y 4 GB de RAM para un rendimiento fluido y una experiencia multimedia excepcional.', Precio: '$119.999', SKU: 'E4ZUCJ69', Stock: '04' },
    { Imagen: './img/Imagen2.jpg', Nombre: 'Notebook Asus Vivobook', Descripcion: 'El portátil Asus Vivobook con procesador Ryzen 7 ofrece un rendimiento excepcional con su potente CPU AMD, 16 GB de RAM y un rápido SSD de 512 GB. Este equipo combina potencia y portabilidad para una experiencia informática versátil y eficiente.', Precio: '$569.999', SKU: 'C5KWZ83Z', Stock: '12' },
    { Imagen: './img/Imagen7.jpg', Nombre: 'Smart TV LED 55" BGH', Descripcion: 'La Smart TV LED 55" BGH B5522US6A Android es una experiencia audiovisual excepcional. Con Android TV, resolución nítida 4K y conectividad inteligente, disfruta de entretenimiento sin límites en una pantalla impresionante.', Precio: '$280.999', SKU: 'VGAXGEWV', Stock: '16' },
    { Imagen: './img/Imagen4.jpg', Nombre: 'Monitor Samsung 24"', Descripcion: 'El Monitor Gamer Samsung F24t35 LED de 24 pulgadas en elegante azul y gris oscuro ofrece una experiencia de juego inmersiva con calidad de color superior y rendimiento excepcional.', Precio: '$113.399', SKU: 'VFHXJRKM', Stock: '14' },
    { Imagen: './img/Imagen3.jpg', Nombre: 'Samsung Galaxy A03', Descripcion: 'El Samsung Galaxy A03 en azul ofrece un rendimiento excepcional con 4 GB de RAM y 64 GB de almacenamiento. Con su elegante diseño, pantalla vibrante y potente cámara, es la elección perfecta para tus necesidades móviles.', Precio: '$69.999', SKU: 'NGEMUWFB', Stock: '17' },
    { Imagen: './img/Imagen10.jpg', Nombre: 'Moto G23 128 GB', Descripcion: 'El Moto G23 en elegante pearl white es un smartphone potente y elegante con 128 GB de almacenamiento y 4 GB de RAM para un rendimiento fluido y una experiencia multimedia excepcional.', Precio: '$119.999', SKU: 'E4ZUCJ69', Stock: '04' },
    { Imagen: './img/Imagen1.jpg', Nombre: 'Smart TV 43" Philips', Descripcion: 'El Android TV Philips LED Full HD de 43 pulgadas (modelo 43PFD6917) en elegante negro ofrece una experiencia visual cautivadora y funciones inteligentes avanzadas para streaming, aplicaciones y juegos, brindando entretenimiento sin límites.', Precio: '$169.999', SKU: 'KR3ZQQY8', Stock: '25' },

]

export default Products;